### ISSUE TITLE
License

### ISSUE THREAD

**Issue by e8johan** [kittykatattack/scaleToWindow#1]
Great work! What license is the scaleToWindow code made available under?

**Comment by kittykatattack** [comment]
Yes, scaleToWindow is licensed under the Kittykatattack Universal License, which is the least restrictive software licence in existence. (It's incalculably less restrictive that either MIT or CC.) So if you want to use the code for anything, include to reverse engineer the code so that the code itself no longer exists, go for it!

**Comment by e8johan** [comment]
Thanks for the clarification!
